/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosDeGuinchoEReboqueRouteImport } from './routes/servicos-de-guincho-e-reboque'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as GuinchoEmSlugRouteImport } from './routes/guincho-em-$slug'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as IndexRouteImport } from './routes/index'

const ServicosDeGuinchoEReboqueRoute =
  ServicosDeGuinchoEReboqueRouteImport.update({
    id: '/servicos-de-guincho-e-reboque',
    path: '/servicos-de-guincho-e-reboque',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoEmSlugRoute = GuinchoEmSlugRouteImport.update({
  id: '/guincho-em-$slug',
  path: '/guincho-em-$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/guincho-em-$slug': typeof GuinchoEmSlugRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/guincho-em-$slug': typeof GuinchoEmSlugRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/guincho-em-$slug': typeof GuinchoEmSlugRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncie'
    | '/cobertura'
    | '/contato'
    | '/guincho-em-$slug'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/cobertura'
    | '/contato'
    | '/guincho-em-$slug'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
  id:
    | '__root__'
    | '/'
    | '/anuncie'
    | '/cobertura'
    | '/contato'
    | '/guincho-em-$slug'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnuncieRoute: typeof AnuncieRoute
  CoberturaRoute: typeof CoberturaRoute
  ContatoRoute: typeof ContatoRoute
  GuinchoEmSlugRoute: typeof GuinchoEmSlugRoute
  ServicosRoute: typeof ServicosRoute
  ServicosDeGuinchoEReboqueRoute: typeof ServicosDeGuinchoEReboqueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos-de-guincho-e-reboque': {
      id: '/servicos-de-guincho-e-reboque'
      path: '/servicos-de-guincho-e-reboque'
      fullPath: '/servicos-de-guincho-e-reboque'
      preLoaderRoute: typeof ServicosDeGuinchoEReboqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-em-$slug': {
      id: '/guincho-em-$slug'
      path: '/guincho-em-$slug'
      fullPath: '/guincho-em-$slug'
      preLoaderRoute: typeof GuinchoEmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnuncieRoute: AnuncieRoute,
  CoberturaRoute: CoberturaRoute,
  ContatoRoute: ContatoRoute,
  GuinchoEmSlugRoute: GuinchoEmSlugRoute,
  ServicosRoute: ServicosRoute,
  ServicosDeGuinchoEReboqueRoute: ServicosDeGuinchoEReboqueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
