/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as IndexRouteImport } from './routes/index'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anuncie' | '/cobertura' | '/contato' | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anuncie' | '/cobertura' | '/contato' | '/servicos'
  id: '__root__' | '/' | '/anuncie' | '/cobertura' | '/contato' | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnuncieRoute: typeof AnuncieRoute
  CoberturaRoute: typeof CoberturaRoute
  ContatoRoute: typeof ContatoRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnuncieRoute: AnuncieRoute,
  CoberturaRoute: CoberturaRoute,
  ContatoRoute: ContatoRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
