/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosDeGuinchoEReboqueRouteImport } from './routes/servicos-de-guincho-e-reboque'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RodoviasValeDoParaibaRouteImport } from './routes/rodovias-vale-do-paraiba'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RemocaoVeicularRouteImport } from './routes/remocao-veicular'
import { Route as PaneSecaRouteImport } from './routes/pane-seca'
import { Route as GuinchoPesadoRouteImport } from './routes/guincho-pesado'
import { Route as GuinchoLeveRouteImport } from './routes/guincho-leve'
import { Route as GuinchoEmChar123slugChar125RouteImport } from './routes/guincho-em-{$slug}'
import { Route as GuinchoDeMotosRouteImport } from './routes/guincho-de-motos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as AutoSocorroRouteImport } from './routes/auto-socorro'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosDeGuinchoEReboqueRoute =
  ServicosDeGuinchoEReboqueRouteImport.update({
    id: '/servicos-de-guincho-e-reboque',
    path: '/servicos-de-guincho-e-reboque',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RodoviasValeDoParaibaRoute = RodoviasValeDoParaibaRouteImport.update({
  id: '/rodovias-vale-do-paraiba',
  path: '/rodovias-vale-do-paraiba',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RemocaoVeicularRoute = RemocaoVeicularRouteImport.update({
  id: '/remocao-veicular',
  path: '/remocao-veicular',
  getParentRoute: () => rootRouteImport,
} as any)
const PaneSecaRoute = PaneSecaRouteImport.update({
  id: '/pane-seca',
  path: '/pane-seca',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoPesadoRoute = GuinchoPesadoRouteImport.update({
  id: '/guincho-pesado',
  path: '/guincho-pesado',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoLeveRoute = GuinchoLeveRouteImport.update({
  id: '/guincho-leve',
  path: '/guincho-leve',
  getParentRoute: () => rootRouteImport,
} as any)
const GuinchoEmChar123slugChar125Route =
  GuinchoEmChar123slugChar125RouteImport.update({
    id: '/guincho-em-{$slug}',
    path: '/guincho-em-{$slug}',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuinchoDeMotosRoute = GuinchoDeMotosRouteImport.update({
  id: '/guincho-de-motos',
  path: '/guincho-de-motos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoSocorroRoute = AutoSocorroRouteImport.update({
  id: '/auto-socorro',
  path: '/auto-socorro',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auto-socorro': typeof AutoSocorroRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/guincho-de-motos': typeof GuinchoDeMotosRoute
  '/guincho-em-{$slug}': typeof GuinchoEmChar123slugChar125Route
  '/guincho-leve': typeof GuinchoLeveRoute
  '/guincho-pesado': typeof GuinchoPesadoRoute
  '/pane-seca': typeof PaneSecaRoute
  '/remocao-veicular': typeof RemocaoVeicularRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rodovias-vale-do-paraiba': typeof RodoviasValeDoParaibaRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auto-socorro': typeof AutoSocorroRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/guincho-de-motos': typeof GuinchoDeMotosRoute
  '/guincho-em-{$slug}': typeof GuinchoEmChar123slugChar125Route
  '/guincho-leve': typeof GuinchoLeveRoute
  '/guincho-pesado': typeof GuinchoPesadoRoute
  '/pane-seca': typeof PaneSecaRoute
  '/remocao-veicular': typeof RemocaoVeicularRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rodovias-vale-do-paraiba': typeof RodoviasValeDoParaibaRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auto-socorro': typeof AutoSocorroRoute
  '/cobertura': typeof CoberturaRoute
  '/contato': typeof ContatoRoute
  '/guincho-de-motos': typeof GuinchoDeMotosRoute
  '/guincho-em-{$slug}': typeof GuinchoEmChar123slugChar125Route
  '/guincho-leve': typeof GuinchoLeveRoute
  '/guincho-pesado': typeof GuinchoPesadoRoute
  '/pane-seca': typeof PaneSecaRoute
  '/remocao-veicular': typeof RemocaoVeicularRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rodovias-vale-do-paraiba': typeof RodoviasValeDoParaibaRoute
  '/servicos': typeof ServicosRoute
  '/servicos-de-guincho-e-reboque': typeof ServicosDeGuinchoEReboqueRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncie'
    | '/auto-socorro'
    | '/cobertura'
    | '/contato'
    | '/guincho-de-motos'
    | '/guincho-em-{$slug}'
    | '/guincho-leve'
    | '/guincho-pesado'
    | '/pane-seca'
    | '/remocao-veicular'
    | '/robots.txt'
    | '/rodovias-vale-do-paraiba'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/auto-socorro'
    | '/cobertura'
    | '/contato'
    | '/guincho-de-motos'
    | '/guincho-em-{$slug}'
    | '/guincho-leve'
    | '/guincho-pesado'
    | '/pane-seca'
    | '/remocao-veicular'
    | '/robots.txt'
    | '/rodovias-vale-do-paraiba'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/anuncie'
    | '/auto-socorro'
    | '/cobertura'
    | '/contato'
    | '/guincho-de-motos'
    | '/guincho-em-{$slug}'
    | '/guincho-leve'
    | '/guincho-pesado'
    | '/pane-seca'
    | '/remocao-veicular'
    | '/robots.txt'
    | '/rodovias-vale-do-paraiba'
    | '/servicos'
    | '/servicos-de-guincho-e-reboque'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnuncieRoute: typeof AnuncieRoute
  AutoSocorroRoute: typeof AutoSocorroRoute
  CoberturaRoute: typeof CoberturaRoute
  ContatoRoute: typeof ContatoRoute
  GuinchoDeMotosRoute: typeof GuinchoDeMotosRoute
  GuinchoEmChar123slugChar125Route: typeof GuinchoEmChar123slugChar125Route
  GuinchoLeveRoute: typeof GuinchoLeveRoute
  GuinchoPesadoRoute: typeof GuinchoPesadoRoute
  PaneSecaRoute: typeof PaneSecaRoute
  RemocaoVeicularRoute: typeof RemocaoVeicularRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RodoviasValeDoParaibaRoute: typeof RodoviasValeDoParaibaRoute
  ServicosRoute: typeof ServicosRoute
  ServicosDeGuinchoEReboqueRoute: typeof ServicosDeGuinchoEReboqueRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos-de-guincho-e-reboque': {
      id: '/servicos-de-guincho-e-reboque'
      path: '/servicos-de-guincho-e-reboque'
      fullPath: '/servicos-de-guincho-e-reboque'
      preLoaderRoute: typeof ServicosDeGuinchoEReboqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rodovias-vale-do-paraiba': {
      id: '/rodovias-vale-do-paraiba'
      path: '/rodovias-vale-do-paraiba'
      fullPath: '/rodovias-vale-do-paraiba'
      preLoaderRoute: typeof RodoviasValeDoParaibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remocao-veicular': {
      id: '/remocao-veicular'
      path: '/remocao-veicular'
      fullPath: '/remocao-veicular'
      preLoaderRoute: typeof RemocaoVeicularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pane-seca': {
      id: '/pane-seca'
      path: '/pane-seca'
      fullPath: '/pane-seca'
      preLoaderRoute: typeof PaneSecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-pesado': {
      id: '/guincho-pesado'
      path: '/guincho-pesado'
      fullPath: '/guincho-pesado'
      preLoaderRoute: typeof GuinchoPesadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-leve': {
      id: '/guincho-leve'
      path: '/guincho-leve'
      fullPath: '/guincho-leve'
      preLoaderRoute: typeof GuinchoLeveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-em-{$slug}': {
      id: '/guincho-em-{$slug}'
      path: '/guincho-em-{$slug}'
      fullPath: '/guincho-em-{$slug}'
      preLoaderRoute: typeof GuinchoEmChar123slugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guincho-de-motos': {
      id: '/guincho-de-motos'
      path: '/guincho-de-motos'
      fullPath: '/guincho-de-motos'
      preLoaderRoute: typeof GuinchoDeMotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-socorro': {
      id: '/auto-socorro'
      path: '/auto-socorro'
      fullPath: '/auto-socorro'
      preLoaderRoute: typeof AutoSocorroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnuncieRoute: AnuncieRoute,
  AutoSocorroRoute: AutoSocorroRoute,
  CoberturaRoute: CoberturaRoute,
  ContatoRoute: ContatoRoute,
  GuinchoDeMotosRoute: GuinchoDeMotosRoute,
  GuinchoEmChar123slugChar125Route: GuinchoEmChar123slugChar125Route,
  GuinchoLeveRoute: GuinchoLeveRoute,
  GuinchoPesadoRoute: GuinchoPesadoRoute,
  PaneSecaRoute: PaneSecaRoute,
  RemocaoVeicularRoute: RemocaoVeicularRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RodoviasValeDoParaibaRoute: RodoviasValeDoParaibaRoute,
  ServicosRoute: ServicosRoute,
  ServicosDeGuinchoEReboqueRoute: ServicosDeGuinchoEReboqueRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
